config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "toppages#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  resources :posts
  get "search", to: "posts#search"
  get "search_tag", to: "posts#search_tag"
  post "/review_complete/:id", to: "posts#review_complete", as: "review_complete"
  delete "/review_incomplete/:id", to: "posts#review_incomplete", as: "review_incomplete"
  get "/toppages", to: "toppages#index"
  get "/graphs", to: "graphs#index"
  devise_scope :user do
    post "user/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contest.rb
# frozen_string_literal: true

class Contest < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :contest_name, presence: true
  validates :contest_number, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :contest
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  validates :question_name, presence: true
  validates :code, presence: true
  validates :correct, presence: true

  enum correct: {
    AC: 1,
    解説AC: 2,
    TLE: 3,
    WA: 4
  }

  enum review_completion: { 未完了: 0, 復習完了: 1 }

  def post_correct?
    if correct == "AC"
      self.review_completion = 1
      self.review_date = Time.current
    else
      self.review_completion = 0
    end
  end

  def save_tag(sent_tags)
    current_tags = tags.pluck(:name) unless tags.nil?
    @old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
    # 古いタグがあれば古いタグを消す
    if @old_tags.present?
      @old_tags.each do |old|
        tags.delete(Tag.find_by(name: old))
      end
    end
    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      tags << new_post_tag
    end
  end

  def old_tag_destroy?(old_tags = @old_tags)
    return if old_tags.blank?

    old_tags.each do |tag_name|
      tag = Tag.find_by(name: tag_name)
      Tag.find_by(id: tag.id).delete if PostTag.where(tag_id: tag.id).count.zero?
    end
  end
end

app/models/post_tag.rb
# frozen_string_literal: true

class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "ゲスト"
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  def index
    @post = current_user.posts
    @ac_num = @post.where(correct: "AC").count
    @commentary_ac_num = @post.where(correct: "解説AC").count
    @tle_num = @post.where(correct: "TLE").count
    @wa_num = @post.where(correct: "WA").count
    @review_completion_num = @post.where(review_completion: "復習完了").count
    @review_incompletion_num = @post.where(review_completion: "未完了").count
    @correct_ratio = @post.count.zero? ? 0 : (100 * @review_completion_num / @post.count).to_f
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post_contest, only: %i[show destroy edit update review_complete review_incomplete]
  before_action :set_tag_list, only: %i[update create]
  PER_PAGE = 10

  def index
    @q = current_user.posts.includes(:contest, :tags).ransack(params[:q])
    @posts = @q.result.page(params[:page]).order(created_at: :desc).per(PER_PAGE)
  end

  def new
    @contest = Contest.new
    @post = @contest.posts.new
    @tag = @post.tags.pluck(:name).join(" ")
  end

  def create
    contest = Contest.create(contest_params)
    @post = contest.posts.new(post_params)
    @post.user_id = current_user.id
    @post.post_correct?
    if @post.save
      @post.save_tag(@tag_list)
      flash[:notice] = t "flash.new"
      redirect_to @post
    else
      flash.now[:alert] = t "flash.new _fail"
      render :new
    end
  end

  def show
    @post_tags = @post.tags
  end

  def destroy
    tags = @post.tags.pluck(:name)
    @post.destroy!
    @post.old_tag_destroy?(tags)
    flash.now[:alert] = t "flash.destroy"
    redirect_to posts_path
  end

  def edit
    @tag = @post.tags.pluck(:name).join(" ")
  end

  def update
    @post.post_correct?
    if @post.update(post_params) && @contest.update(contest_params)
      @post.save_tag(@tag_list)
      @post.old_tag_destroy?
      flash[:notice] = t "flash.update"
      redirect_to @post
    else
      flash.now[:alert] = t "flash.update_fail"
      render :edit
    end
  end

  def search
    @q = current_user.posts.includes(:contest, :tags).ransack(search_params)
    @posts = @q.result.page(params[:page]).per(PER_PAGE)
  end

  def search_tag
    @tag_list = Tag.all
    @tag = Tag.find(params[:id])
    @posts = @tag.posts.includes(:contest, :tags).page(params[:page]).per(PER_PAGE)
  end

  def review_complete
    @post.review_date = Time.current
    @post.review_completion = 1
    @post.save
    redirect_back(fallback_location: posts_path)
  end

  def review_incomplete
    @post.review_completion = 0
    @post.save
    redirect_back(fallback_location: posts_path)
  end

  private

  def set_tag_list
    @tag_list = params[:post][:name].split
  end

  def search_params
    params.require(:q).permit!
  end

  def set_post_contest
    @post = Post.find(params[:id])
    @contest = Contest.find(@post.contest_id)
  end

  def post_params
    params.require(:post).permit(:question_name, :code, :comment, :correct, :contest_id, :image)
  end

  def contest_params
    params.require(:post).permit(:contest_name, :contest_number)
  end
end

app/controllers/toppages_controller.rb
# frozen_string_literal: true

class ToppagesController < ApplicationController
  def index; end
end

app/controllers/users/passwords_controller.rb
module Users
  class PasswordsController < Devise::PasswordsController
    before_action :ensure_normal_user, only: :create

    def ensure_normal_user
      redirect_to new_user_session_path, alert: "ゲストユーザーのパスワード再設定はできません。" if params[:user][:email].casecmp("guest@example.com").zero?
    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :ensure_normal_user, only: %i[update destroy]

    def ensure_normal_user
      redirect_to edit_user_registration_path, alert: "ゲストユーザーは削除できません" if resource.email == "guest@example.com"
    end
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    def guest_sign_in
      sign_in User.guest
      redirect_to posts_path, notice: "ゲストユーザーとしてログインしました。"
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/graphs/index.html.erb
<div class="base-container">
<% if @post.count==0%>
  <h1>投稿はまだありません。投稿してみましょう！！</h1>
<% else%>
  <h1 class="top"><%= current_user.nickname.present? ? "#{current_user.nickname}":"#{current_user.email}"%>さんの達成状況</h1>
    <h2>総解答数:<%= @post.count%>題</h2>
    <%= area_chart @post.group_by_day(:created_at).count,xtitle:"日付",ytitle:"投稿数"%>


    <h2>正誤内訳</h2>
    <table class="table table-striped table-bordered table-sm">
     <thead>
        <tr>
          <th>正誤</th>
          <th>題数</th>
          <th>占有率</th>
        </tr>
      </thead>
      <tbody>
        <tr>
           <td data-label="正誤"><button type="button" class="btn btn-success" disabled>AC</button></td>
           <td data-label="題数"><%=@ac_num%></td>
           <td data-label="占有率"><%=(100 * @ac_num/ @post.count).to_f%>%</td>
        </tr>
        <tr>
           <td data-label="正誤"><button type="button" class="btn btn-secondary" disabled>解説AC</button></td>
           <td data-label="題数"><%=@commentary_ac_num%></td> 
           <td data-label="占有率"><%=(100 * @commentary_ac_num/ @post.count).to_f %>%</td>
        </tr>
        <tr>
           <td data-label="正誤"><button type="button" class="btn btn-warning" disabled>TLE</button></td>
           <td data-label="題数"><%=@tle_num%></td>
           <td data-label="占有率"><%=(100 * @tle_num/ @post.count).to_f%>%</td>
        </tr>
        <tr>
           <td data-label="正誤"><button type="button" class="btn btn-warning" disabled>WA</button></td>
           <td data-label="題数"><%=@wa_num%></td>
           <td data-label="占有率"><%=(100 * @wa_num/ @post.count).to_f %>%</td>
        </tr>
      </tbody>
    </table>
        
    <%= pie_chart [['AC',@ac_num], ['解説AC',@commentary_ac_num],['TLE',@tle_num],['WA',@wa_num]],colors: ["#3cb371", "#a9a9a9","#ffff00","#ffff00"] %>

    
    <h2>復習完了率:<%= @correct_ratio %>%</h2>

    <table class="table table-striped table-bordered table-sm">
     <thead>
        <tr>
          <th>復習状態</th>
          <th>題数</th>
          <th>占有率</th>
        </tr>
      </thead>
      <tbody>
        <tr>
           <td data-label="復習状態"><button type="button" class="btn btn-outline-success" disabled>復習完了</button></td>
           <td data-label="題数"><%=@review_completion_num%></td>
           <td data-label="占有率"><%=(100 * @review_completion_num/ @post.count).to_f%>%</td>
        </tr>
        <tr>
           <td data-label="復習状態"><button type="button" class="btn btn-outline-danger" disabled>未完了</button></td>
           <td data-label="題数"><%=@review_incompletion_num%></td> 
           <td data-label="占有率"><%=(100 * @review_incompletion_num/ @post.count).to_f %>%</td>
        </tr>
      </tbody>
    </table>


    <%= pie_chart [['復習完了', @review_completion_num],['未完了',@review_incompletion_num]],colors: ["#3cb371", "#ff0000"]%>
<%end%>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark fixed-top" style="background-color:#0000cd">
<span class="navbar-brand title">コードメモリー</span>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
     <%= link_to 'トップページ',toppages_path,class: "nav-item nav-link active" %>
     <% if user_signed_in?%>
          <%= link_to "投稿一覧", posts_path,class: "nav-item nav-link active" %>
          <%= link_to "新規投稿", new_post_path,class: "nav-item nav-link active" %>
          <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown">
            <%= current_user.nickname.present? ? "#{current_user.nickname}":"#{current_user.email}"%>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "ユーザー情報・編集",edit_user_registration_path,class: "dropdown-item" %>
            <%= link_to "達成状況",graphs_path,class: "dropdown-item" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか?"},class: "dropdown-item" %>
          </div>
          </li>
     <% else %>
          <%= link_to "新規登録",new_user_registration_path ,class: "nav-item nav-link active" %>
          <%= link_to "ログイン", new_user_session_path,class: "nav-item nav-link active" %>
          <%= link_to "ゲストログイン", user_guest_sign_in_path,method: :post,class: "nav-item nav-link active" %>
     <% end %>
     </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script type="text/javascript" async src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML"></script>
  </head>
  <body>
    <header>
      <meta name=viewport content="width=device-width, initial-scale=1">
      <%= render "layouts/header"%>
      <main>
        <%= yield %>
      </main>
      <footer>
        <p>&copy; ArataMatsuyama.2022</p>
      </footer>
    </body>
  </html>

app/views/posts/_form.html.erb
<%= form_with model:@post,local: true do |form|%>
  <div class="form-group">
    <%= form.label :contest_name, "コンテスト名" %>
    <%= form.text_field :contest_name ,required: true,value: @contest.contest_name,class: "form-control contest-name form",placeholder:"ABC"%>
  </div>

  <div class="form-group">
    <%= form.label :contest_number,"コンテスト回"%>
    <%= form.text_field :contest_number,required: true,value: @contest.contest_number,class: "form-control contest-number form",placeholder:"1"%>
  </div>

  <div class="form-group">
    <%= form.label :question_name,"問題名" %>
    <%= form.text_field :question_name,required: true,class: "form-control question-name form",placeholder:"max-min-problem"%>
  </div>

  <div class="form-group">
    <%= form.label :name ,"タグ"%>
    <p>関連するタグを半角スペースで入力</p>
    <%= form.text_field :name,value: @tag,class: "form-control form" ,placeholder:"動的計画法 苦手"%>
  </div>
  
  <%= form.label :correct, "正誤"%><br>
  <%= form.select :correct,Post.corrects.keys,class: "form"%>


  <div class="form-group">
    <%= form.label :code, "コード" %>
    <%= form.text_area :code,required: true,class: "form-control form",size:"10x20",placeholder:"print(Hello World)"%>
  </div>


  <div class="form-group">
    <%= form.label :comment, "コメント" %>
    <p>TeX記法で数式表示可</p>
    <%= form.text_area :comment,class: "form-control form",size:"10x10",placeholder:"難しかった,要復習,e^{a+b}"%>
  </div>

  <div class="form-group">
    <%= form.label :image, "メモ" %>
    <p>メモ画像があればこちらへ</p>
    <%= form.file_field :image, accept: "image/png,image/jpeg,image/gif"%>
  </div>


<%= form.submit button_value%>
<% end %>

app/views/posts/_result.html.erb
<table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th scope="col">コンテスト</th>
        <th scope="col">投稿日</th>
        <th scope="col">問題名</th>
        <th scope="col">タグ</th>
        <th scope="col">正誤</th>
        <th scope="col">復習状態</th>
        <th scope="col">その他</th>


    </thead>

    <tbody>
    <% @posts.each do |post| %>
      <tr>
      <td data-label="コンテスト"><%= post.contest.contest_name%><%=post.contest.contest_number%></td>

      <td data-label="投稿日"><%= l post.created_at%></td>

      <td data-label="問題名"><%= post.question_name %></td>

      <td data-label="タグ">
      <% post.tags.each do |tag|%>
          <%= link_to tag.name, search_tag_path(id: tag.id),class:"btn btn-link"%>
      <% end %>
      </td>

      
      <%if post.correct=="AC"%>
        <td data-label="正誤"><button type="button" class="btn btn-success" disabled><%= post.correct %></button></td>
      <% elsif post.correct=="解説AC"%>
        <td data-label="正誤"><button type="button" class="btn btn-secondary" disabled><%= post.correct %></button></td>
      <%else%>
        <td data-label="正誤"><button type="button" class="btn btn-warning" disabled><%= post.correct %></button></td>
      <%end%>
      


      <% if post.review_completion=="未完了"%>
      <td data-label="復習状態"><%= render "review_incomplete",post: post%></td>
      <% else %>
      <td data-label="復習状態"><%= render "review_complete",post: post%></td>
      <%end%>
      

      <td class="text-nowrap last" data-label="その他">
       <%= link_to "詳細",post_path(post),class:"btn btn-success"%>
       <%= link_to "編集",edit_post_path(post),class:"btn btn-primary"%>
       <%= link_to "削除",post_path(post), method: :delete, data: { confirm: "削除しますか?" },class:"btn btn-danger"%>
      </td>
    <% end %>
    </tbody>
  </table>

app/views/posts/_review_complete.html.erb
<%= link_to "復習完了",review_incomplete_path(post), method: :delete, remote: true%>

app/views/posts/_review_incomplete.html.erb
<%= link_to "未完了", review_complete_path(post), method: :post, remote: true %>

app/views/posts/create.html.erb
<div class="base-container">
<%= render "layouts/flash_messages" %>
<h1>登録完了が完了しました</h1>
<%= link_to "一覧に戻る",posts_path%>
</div>

app/views/posts/edit.html.erb
<div class="base-container">
<%= render "layouts/flash_messages" %>
<h1>編集</h1>
<%= render "form",button_value:"更新"%>
<%= link_to "前の画面に戻る",:back,class:"btn btn-dark back mt-3"%>
<%= link_to "一覧に戻る", posts_path,class:"btn btn-dark back mt-3"%>
</div>

app/views/posts/new.html.erb
<div class="base-container">
<%= render "layouts/flash_messages" %>
<h1 class="top">新規記録</h1>
<%= render "form",button_value: "投稿"%>
<%= link_to "前の画面に戻る",:back,class:"btn btn-dark mt-3"%>
<%= link_to "一覧に戻る", posts_path,class:"btn btn-dark mt-3"%>
</div>

app/views/posts/search.html.erb
  <div class="base-container">
  <%= render "layouts/flash_messages" %>
  <% if @posts.present?%>
    <h1 class="top">検索結果</h1>
  <%= render "result"%>
  <%else%>
    <h1>条件に一致する投稿はありません</h1>
  <%end%>
  <%= paginate @posts%>
  <%= link_to "前の画面に戻る",:back,class:"btn btn-dark"%>
  <%= link_to "一覧に戻る", posts_path,class:"btn btn-dark"%>
</div>

app/views/posts/search_tag.html.erb
  <div class="base-container">
  <%= render "layouts/flash_messages" %>
  <% if @posts.present?%>
  <h1 class="top">「<%= @tag.name %>」のタグが付いた問題</h1>
  <%= render "result"%>
  <%else%>
    <h1>条件に一致する投稿はありません</h1>
  <%end%>
  <%= paginate @posts%>
  <%= link_to "前の画面に戻る",:back,class:"btn btn-dark"%>
  <%= link_to "一覧に戻る", posts_path,class:"btn btn-dark"%>
</div>

app/views/posts/show.html.erb
<div class="base-container">
<%= render "layouts/flash_messages" %>
  <h1 class="top">詳細情報</h1>
  <%= link_to "編集",edit_post_path(@post),class:"btn btn-primary mb-3"%>
  <%= link_to "削除",post_path(@post), method: :delete, data: { confirm: "削除しますか?" },class:"btn btn-danger mb-3"%>
  <table class="table table-bordered table-striped show">

  <tbody>
    <tr>
    <th scope="row">コンテスト</th>
    <td><%= @post.contest.contest_name %><%=@post.contest.contest_number%></td>
    </tr>
    
    <tr>
    <th scope="row">問題名</th>
    <td><%= @post.question_name %></td>
    </tr>

    <tr>
    <th scope="row">投稿日</th>
    <td><%= l @post.created_at %></td>
    </tr>

    <tr>
    <th scope="row">タグ</th>
    <td>
    <% @post_tags.each do |tag|%>
    <%= link_to tag.name,search_tag_path(id: tag.id),class:"btn btn-link"%>
    <% end %>
    </td>
    </tr>

    <tr>
    <th scope="row">結果</th>
    <%if @post.correct=="AC"%>
    <td><button type="button" class="btn btn-success" disabled><%= @post.correct %></button></td>
    <% elsif @post.correct=="解説AC"%>
      <td><button type="button" class="btn btn-secondary" disabled><%= @post.correct %></button></td>
    <%else%>
      <td><button type="button" class="btn btn-warning" disabled><%= @post.correct %></button></td>
    <%end%>
    </tr>
    
    <% if @post.review_completion=="未完了"%>
      <tr><th scope="row">復習状態</th><td><button type="button" class="btn btn-outline-danger" ><%= render "review_incomplete",post: @post%></button></td></tr>
    <% else %>
      <tr><th scope="row">復習状態</th><td><button type="button" class="btn btn-outline-success" disabled><%= render "review_complete",post: @post%></button></td></tr>
      <tr><th scope="row">最終復習日</th><td><%= l @post.review_date%></td></tr>
    <%end%>
  </tbody>
  </table>




  <div>
  <pre><code class="code"><%= @post.code%></code></pre>
  </div>
  <script type="text/javascript" async src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML"></script>

  <div class="box">
    <span class="box-title">コメント</span>
    <p class="comment"><%= @post.comment%></p>
  </div>
  <script>hljs.highlightAll();</script>


  <% if @post.image? %>
    <span class="memo-title">解説メモ</span>
    <p class="image"><%= image_tag @post.image.url%></p>
  <% end %>
  <%= link_to "一覧に戻る", posts_path,class:"btn btn-dark mt-3"%>
</div>


<script>
$(document).ready(function(){
    if (window.name != "reload_complete") {
        location.reload();
        window.name = "reload_complete";
    } else {
        window.name = "";
    }
});
</script>

app/views/reviews/review_complete.js.erb
document.getElementById('post-<%= @post.id %>').innerHTML = '<%= j render("posts/review_complete", post: @post) %>'

app/views/reviews/review_incomplete.js.erb
document.getElementById('post-<%= @post.id %>').innerHTML = '<%= j render("posts/review_incomplete", post: @post) %>'

app/views/toppages/index.html.erb
<section class="wrapper">
<%= render "layouts/flash_messages" %>
    <div class="container">
        <div class="content">
        <p class="title">コードメモリー</p>
        <p class="phrase">コードメモリーは競技プログラミングの<br class="br-pc">復習を<br class="br-sp">サポートするサービスです</p>
        <div class="top-botton">
        <%= link_to "新規登録",new_user_registration_path,class:"btn btn-danger btn-lg"%>
        <%= link_to "ログイン", new_user_session_path,class:"btn btn-primary btn-lg"%>
        <%= link_to "ゲストログイン", user_guest_sign_in_path,method: :post,class:"btn btn-primary btn-lg gest-login-btn" %>
        </div>
    </div>
</section>

<section class="content container">
  
        <p class="content_title"> どんな機能が<br class="br-sp">あるの？</p>

        <div class="card-deck">
          <div class="card text-dark bg-light" style="width: 18rem"> 
            <%= image_tag asset_path('post_new.png') %>
            <div class="card-body">
              <h2 class="card-title">記録投稿機能</h2>
              <p class="card-text">自分が解いた問題についての情報を投稿！画像投稿もできるので、<br class="br-pc">解答時のメモも保存可能。</p>
            </div>
          </div>

          <div class="card text-dark bg-light" style="width: 18rem"> 
            <%= image_tag asset_path('tag.png') %>
            <div class="card-body">
              <h2 class="card-title">タグ付け機能</h2>
              <p class="card-text">タグをつけることで問題を類別。<br class="br-pc">また、タグをクリックすると同じ<br class="br-pc">タグのついた問題のみ表示可能！</p>
            </div>
          </div>


          <div class="card text-dark bg-light" style="width: 18rem"> 
            <%= image_tag asset_path('output.png') %>
            <div class="card-body ">
              <h2 class="card-title">コメント機能</h2>
              <p class="card-text">問題の解答やポイントを<br class="br-sp">自分で書くことで知識をアウトプット。<br class="br-pc">TeX記法に<br class="br-sp">対応してるので数式表示も可能。</p>
            </div>
          </div>
        </div>


        <div class="card-deck">
          <div class="card text-dark bg-light" style="width: 18rem"> 
              <%= image_tag asset_path('review_tags.png') %>
              <div class="card-body">
                <h2 class="card-title">復習済み機能</h2>
                <p class="card-text">復習済みか未復習か表示！<br class="br-pc">クリックすることで<br class="br-sp">切り替え可能。</p>
              </div>
          </div>

          <div class="card text-dark bg-light" style="width: 18rem"> 
              <%= image_tag asset_path('graph.png') %>
              <div class="card-body">
                <h2 class="card-title">達成状況表示機能</h2>
                <p class="card-text">何問解いたか,復習はどの程度<br class="br-pc">終わっているかを表示。</p>
              </div>
          </div>

          <div class="card text-dark bg-light" style="width: 18rem"> 
              <%= image_tag asset_path('research.png') %>
              <div class="card-body ">
                <h2 class="card-title">検索機能</h2>
                <p class="card-text">コンテスト名,問題名,正誤<br class="br-sp">などで<br class="br-pc">記録を検索できる！</p>
              </div>
          </div>
        </div>
        </p>
    
</section>

<section class="bottom">
    <p>さあ、今すぐ始めよう！</p>
    <div class="bottom-botton"><%= link_to "新規登録",new_user_registration_path,class:"btn btn-danger btn-lg"%></div>
</section>